### ISSUE TITLE
[Crash]: 1.19 SERVER PACK ALLTHEWIZARDGEAR

### ISSUE THREAD

**Issue by Nox-Veneficus** [AllTheMods/ATM-10#1148]
### Possible Fixes

?

### Modpack Version

1.19

### What happened?

[22:14:54.757] [main/ERROR] [loading.moddiscovery.ModFile/LOADING]: Access transformer file META-INF/accesstransformer.cfg provided by mod allthewizardgear does not exist! 
Exception in thread "main" 
java.lang.module.FindException: Module org.yaml.snakeyaml not found, required by space.arim.dazzleconf.ext.snakeyaml
        at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
        at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:491)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:90)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:87)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)

### Crash Log

panel dose not gen one.

**Comment by alekthefirst** [comment]
Looks like you dont have all the mods expected of version 1.19 or at least they aren't all up to date
