### ISSUE TITLE
[Crash]: Can't start server on linux (using crafty4) from 1.20 and later

### ISSUE THREAD

**Issue by Fisshy86** [AllTheMods/ATM-10#1236]
### Possible Fixes

No

### Modpack Version

1.20 and later

### What happened?

I'm using crafty4 to host and manage servers,  the way I usually update server is to create a new one by downloading the serverfiles from Curse,  then run the neoforge-installer to create server and server jar,  I then zip everything and upload it to crafty to import it, select the root folder and path to the server.jar file.  This works flawlessly up to (and including) version 1.19.  
This issue happens on completely fresh install, not using my world or anything.

I tried 1.20, 1.21, 1.22 and today 1.23 all with the same result. 

The same issues have not been observed on my windows machine, where I can start the server without an issue.

Crafty4 version: 4.4.4
Java version: openjdk 21.0.4 2024-07-16
OpenJDK Runtime Environment (build 21.0.4+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 21.0.4+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)

After versison 1.19, I get the logs as I attached below (crash of server i used the debug log,  both logs are in the same gist. 
I'll also attach the stacktrace here, since it might be hard to read it in the debug log (at least for me, since I don't quite get it)
```
[11:12:30] [main/WARN] [mixin/]: Method overwrite conflict for setChanged in irons_spellbooks.mixins.json:LecternBlockEntityMixin from mod irons_spellbooks, previously written by net.mehvahdjukaar.amendments.mixins.LecternBlockEntityMixin. Skipping method.
[11:12:30] [main/WARN] [mixin/]: Method overwrite conflict for getUpdatePacket in irons_spellbooks.mixins.json:LecternBlockEntityMixin from mod irons_spellbooks, previously written by net.mehvahdjukaar.amendments.mixins.LecternBlockEntityMixin. Skipping method.
[11:12:30] [main/WARN] [mixin/]: Method overwrite conflict for getUpdateTag in irons_spellbooks.mixins.json:LecternBlockEntityMixin from mod irons_spellbooks, previously written by net.mehvahdjukaar.amendments.mixins.LecternBlockEntityMixin. Skipping method.
[11:12:30] [main/INFO] [ne.ne.co.Co.apothic_enchanting/COREMODLOG]: Replaced 1 calls to Enchantment#getMaxLevel() in net/minecraft/world/item/enchantment/Enchantment
[11:12:30] [main/WARN] [mixin/]: Method overwrite conflict for scheduleRandomTick in corgilib-common.mixins.json:chunk.MixinChunkAccess from mod corgilib, previously written by dev.corgitaco.ohthetreesyoullgrow.mixin.chunk.MixinChunkAccess. Skipping method.
[11:12:30] [main/WARN] [mixin/]: Method overwrite conflict for getScheduledRandomTicks in corgilib-common.mixins.json:chunk.MixinChunkAccess from mod corgilib, previously written by dev.corgitaco.ohthetreesyoullgrow.mixin.chunk.MixinChunkAccess. Skipping method.
[11:12:31] [main/INFO] [ne.ne.co.Co.apothic_enchanting/COREMODLOG]: Patching FishingHook#catchingFish
[11:12:31] [main/INFO] [ne.ne.co.Co.apothic_enchanting/COREMODLOG]: Replaced 1 calls to Enchantment#getMaxLevel() in net/minecraft/world/level/storage/loot/functions/EnchantRandomlyFunction
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.neoforged.serverstarterjar.Main.mainLaunch(Main.java:266)
	at net.neoforged.serverstarterjar.Main.main(Main.java:70)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.neoforged.serverstarterjar.Main8.main(Main8.java:19)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128)
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32)
	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 15 more
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/moonlight@1.21-2.17.5/net.mehvahdjukaar.moonlight.api.map.MapDataRegistry.<clinit>(MapDataRegistry.java:29)
	at TRANSFORMER/moonlight@1.21-2.17.5/net.mehvahdjukaar.moonlight.api.map.decoration.MLMapDecorationType.<clinit>(MLMapDecorationType.java:45)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.loot.functions.ExplorationMapFunction.mdafc06b$supplementaries$lambda$supp$modifyCodec$7$0(ExplorationMapFunction.java:628)
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.loot.functions.ExplorationMapFunction.handler$zfb000$supplementaries$supp$modifyCodec(ExplorationMapFunction.java:616)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.loot.functions.ExplorationMapFunction.<clinit>(ExplorationMapFunction.java:37)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.loot.functions.LootItemFunctions.<clinit>(LootItemFunctions.java:45)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer.singletonFields(LootPoolSingletonContainer.java:43)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.loot.entries.EmptyLootItem.lambda$static$0(EmptyLootItem.java:14)
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.loot.entries.EmptyLootItem.<clinit>(EmptyLootItem.java:14)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.loot.entries.LootPoolEntries.<clinit>(LootPoolEntries.java:13)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.registries.BuiltInRegistries.lambda$static$23(BuiltInRegistries.java:179)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.registries.BuiltInRegistries.lambda$internalRegister$48(BuiltInRegistries.java:319)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.registries.BuiltInRegistries.lambda$createContents$49(BuiltInRegistries.java:332)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.registries.BuiltInRegistries.createContents(BuiltInRegistries.java:331)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.registries.BuiltInRegistries.bootStrap(BuiltInRegistries.java:325)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:53)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:120)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 21 more
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at java.base/java.util.ImmutableCollections$SetN.contains(ImmutableCollections.java:944)
	at TRANSFORMER/kubejs@2101.7.1-build.181/dev.latvian.mods.kubejs.registry.RegistryType$Scanner.scan(RegistryType.java:191)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceKey.handler$cba000$kubejs$kjs$getKeyStackTraces(ResourceKey.java:1037)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceKey.<init>(ResourceKey.java:42)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceKey.handler$zcd000$modernfix$createEfficient(ResourceKey.java:522)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceKey.create(ResourceKey.java)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceKey.createRegistryKey(ResourceKey.java:30)
	at TRANSFORMER/moonlight@1.21-2.17.5/net.mehvahdjukaar.moonlight.core.map.MapDataInternal.<clinit>(MapDataInternal.java:47)
	... 42 more
```

### Crash Log

https://gist.github.com/Fisshy86/e5c7caccd1ae7babe2177e686a79de72

### Latest.Log

https://gist.github.com/Fisshy86/e5c7caccd1ae7babe2177e686a79de72

**Comment by pietro-lopes** [comment]
This is a kubejs issue, we are waiting for a release.
If you want a fix before they release, join ATM10 Discord and ping me `@Uncandango`
