### ISSUE TITLE
[Bug]: KubeJS wrong path for MysticalAgriculture cropsInfo.json

### ISSUE THREAD

**Issue by Floo42** [AllTheMods/ATM-10#1238]
### Possible Fixes

Yes

### Modpack Version

1.23

### What happened?

The path indicated in the file kubejs/server_scripts/mods/MysticalAgriculture/Crops.js is seemingly wrong due to the case :

Actual line (54) :
`JsonIO.write('kubejs/server_scripts/mods/mysticalagriculture/cropInfo.json', JsonExport)`

Should be :
`JsonIO.write('kubejs/server_scripts/mods/MysticalAgriculture/cropInfo.json', JsonExport)`

Otherwise Linux servers cannot find the file and it generates an error (File not found)

### latest.log

<details>
  <summary>Error details</summary>

> [23Nov2024 17:45:35.978] [main/ERROR] [KubeJS Server/]: JsonIO.java#95: Error in 'ServerEvents.recipes': java.nio.file.NoSuchFileException: [server_path]/kubejs/server_scripts/mods/mysticalagriculture/cropInfo.json
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]: java.nio.file.NoSuchFileException: [server_path]/kubejs/server_scripts/mods/mysticalagriculture/cropInfo.json
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:482)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at java.nio.file.Files.newOutputStream(Files.java:227)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at java.nio.file.Files.newBufferedWriter(Files.java:2988)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at java.nio.file.Files.newBufferedWriter(Files.java:3036)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at …kubejs.util.JsonIO.write(JsonIO.java:95)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at java.lang.reflect.Method.invoke(Method.java:580)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at …rhino.MemberBox.invoke(MemberBox.java:211)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:468)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at …rhino.Interpreter.interpretLoop(Interpreter.java:988)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at …rhino.Interpreter.interpret(Interpreter.java:372)
[23Nov2024 17:45:35.979] [main/ERROR] [KubeJS Server/]:   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …rhino.Context.callSync(Context.java:1055)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …rhino.Context.doTopCall(Context.java:1072)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …rhino.Context.callSync(Context.java:1055)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …rhino.Context.callSync(Context.java:1055)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:127)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …rhino.VMBridge$AdapterInvocationHandler.invoke(VMBridge.java:75)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at TRANSFORMER/jdk.proxy4/jdk.proxy4.$Proxy116.onEvent(Unknown Source)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:41)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …kubejs.event.EventHandler.postInternal(EventHandler.java:229)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …kubejs.event.EventHandler.post(EventHandler.java:186)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …kubejs.recipe.RecipesKubeEvent.postEvent(RecipesKubeEvent.java:300)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at …kubejs.recipe.RecipesKubeEvent.post(RecipesKubeEvent.java:180)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at net.minecraft.world.item.crafting.RecipeManager.handler$cao000$kubejs$customRecipesHead(RecipeManager.java:4077)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at net.minecraft.world.item.crafting.RecipeManager.apply(RecipeManager.java)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at net.minecraft.world.item.crafting.RecipeManager.apply(RecipeManager.java:36)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at net.minecraft.server.packs.resources.SimplePreparableReloadListener.lambda$reload$1(SimplePreparableReloadListener.java:19)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[23Nov2024 17:45:35.980] [main/ERROR] [KubeJS Server/]:   at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:69)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at net.minecraft.Util.blockUntilDone(Util.java:872)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at net.minecraft.Util.blockUntilDone(Util.java:861)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at net.minecraft.server.Main.main(Main.java:195)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at java.lang.reflect.Method.invoke(Method.java:580)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[23Nov2024 17:45:35.981] [main/ERROR] [KubeJS Server/]:   at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[23Nov2024 17:45:35.982] [main/ERROR] [KubeJS Server/]:   at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
[23Nov2024 17:45:35.982] [main/ERROR] [KubeJS Server/]:   at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)

  </details>

**Comment by Floo42** [comment]
Edit : it seems it was already fixed and it should be available in the next version, I close this issue
