### ISSUE TITLE
[Bug]: Can't start server on macOS

### ISSUE THREAD

**Issue by TrueCyan** [AllTheMods/ATM-10#1489]
### Possible Fixes

Yes

### Modpack Version

2.8

### What happened?

I tried to update the server from 2.7 to 2.8, but a crash occurred. I downloaded the server files from scratch and tried running it again, but the crash still occurred. I run the server on a Mac, so I tried running it on Windows to see if it was a problem with the OS, and it worked fine.

Below is the log when the crash occurred on Mac.

Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128)
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32)
	at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 8 more
Caused by: java.lang.ExceptionInInitializerError
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.<clinit>(MixinBlockStateBase.java:1463)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition.lambda$new$3(StateDefinition.java:64)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:807)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:59)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition$Builder.create(StateDefinition.java:160)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.Block.<init>(Block.java:187)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:20)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:46)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.FireBlock.bootStrap(FireBlock.java:342)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:45)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:120)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 14 more
Caused by: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Reference2ObjectMaps$EmptyMap cannot be cast to class it.unimi.dsi.fastutil.objects.Reference2ObjectArrayMap (it.unimi.dsi.fastutil.objects.Reference2ObjectMaps$EmptyMap and it.unimi.dsi.fastutil.objects.Reference2ObjectArrayMap are in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP' @1990a65e)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateHolder.replacePropertyMap(StateHolder.java:574)
	at TRANSFORMER/ferritecore@7.0.2/malte0811.ferritecore.impl.StateHolderImpl.populateNeighbors(StateHolderImpl.java:34)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateHolder.populateNeighbours(StateHolder.java:552)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:71)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition$Builder.create(StateDefinition.java:160)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.material.Fluid.<init>(Fluid.java:32)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.material.EmptyFluid.<init>(EmptyFluid.java:15)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.material.Fluids.<clinit>(Fluids.java:7)
	... 27 more

### latest.log

https://gist.github.com/TrueCyan/726c2eb1490485214801f7a6d2736c48

**Comment by sorbatdev** [comment]
Came to look for this error, same for me in CentOS 8. Main reason seems to be:

> Caused by: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Reference2ObjectMaps$EmptyMap cannot be cast to class it.unimi.dsi.fastutil.objects.Reference2ObjectArrayMap (it.unimi.dsi.fastutil.objects.Reference2ObjectMaps$EmptyMap and it.unimi.dsi.fastutil.objects.Reference2ObjectArrayMap are in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP'

**Comment by zaciam** [comment]
+1

**Comment by JustinHowes01** [comment]
+1 here as well. Fedora Server
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
        at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136)
        at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:128)
        at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonServerLaunchHandler.runService(CommonServerLaunchHandler.java:32)
        at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
        ... 8 more
Caused by: java.lang.ExceptionInInitializerError
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.<clinit>(MixinBlockStateBase.java:1463)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition.lambda$new$3(StateDefinition.java:64)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:59)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition$Builder.create(StateDefinition.java:160)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.Block.<init>(Block.java:187)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.AirBlock.<init>(AirBlock.java:20)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:46)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.FireBlock.bootStrap(FireBlock.java:342)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:45)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.Main.main(Main.java:120)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 14 more
Caused by: java.lang.ClassCastException: class it.unimi.dsi.fastutil.objects.Reference2ObjectMaps$EmptyMap cannot be cast to class it.unimi.dsi.fastutil.objects.Reference2ObjectArrayMap (it.unimi.dsi.fastutil.objects.Reference2ObjectMaps$EmptyMap and it.unimi.dsi.fastutil.objects.Reference2ObjectArrayMap are in module it.unimi.dsi.fastutil@8.5.12 of loader 'MC-BOOTSTRAP' @5891e32e)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateHolder.replacePropertyMap(StateHolder.java:574)
        at TRANSFORMER/ferritecore@7.0.2/malte0811.ferritecore.impl.StateHolderImpl.populateNeighbors(StateHolderImpl.java:34)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateHolder.populateNeighbours(StateHolder.java:552)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition.<init>(StateDefinition.java:71)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.state.StateDefinition$Builder.create(StateDefinition.java:160)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.material.Fluid.<init>(Fluid.java:32)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.material.EmptyFluid.<init>(EmptyFluid.java:15)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.material.Fluids.<clinit>(Fluids.java:7)
```

**Comment by johskar** [comment]
Fheck file/folder permissions throughout the folder it extracts to,

Looksl like the 2.8 server zip extracts with readonly rights for alot of files and folders that should have write permissions.

Found out when trying to delete before extracting again as I was hitting similar errors.
Would not let me cause the user dould not write to the files/folders.

**Comment by JustinHowes01** [comment]
> Check file/folder permissions throughout the folder it extracts to,
> 
> Looksl like the 2.8 server zip extracts with readonly rights for alot of files and folders that should have write permissions.
> 
> Found out when trying to delete before extracting again as I was hitting similar errors. Would not let me cause the user dould not write to the files/folders.

Yep, that seems to be the issue. For whoever sees this, just run the command `chmod -R +rw <server directory>`, and it should fix it! Thanks @johskar!

**Comment by TrueCyan** [comment]
> > Check file/folder permissions throughout the folder it extracts to,
> > Looksl like the 2.8 server zip extracts with readonly rights for alot of files and folders that should have write permissions.
> > Found out when trying to delete before extracting again as I was hitting similar errors. Would not let me cause the user dould not write to the files/folders.
> 
> Yep, that seems to be the issue. For whoever sees this, just run the command `chmod -R +rw <server directory>`, and it should fix it! Thanks @johskar!

It's fixed on my server too. Thanks.

**Comment by zaciam** [comment]
Great. Thank you.
