### ISSUE TITLE
`java.io.FileNotFoundException: allthetweaks:textures/icons/icon_16x16.png`

### ISSUE THREAD

**Issue by Lolothepro** [AllTheMods/ATM-10#193]
```
java.io.FileNotFoundException: allthetweaks:textures/icons/icon_16x16.png
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.ResourceProvider.lambda$getResourceOrThrow$1(ResourceProvider.java:23) ~[client-1.21-20240613.152323-srg.jar%23365!/:?] {re:classloading,re:mixin}
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.ResourceProvider.getResourceOrThrow(ResourceProvider.java:23) ~[client-1.21-20240613.152323-srg.jar%23365!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/minecraft@1.21/net.minecraft.server.packs.resources.ResourceProvider.open(ResourceProvider.java:27) ~[client-1.21-20240613.152323-srg.jar%23365!/:?] {re:classloading,re:mixin}
	at TRANSFORMER/allthetweaks@2.4.2/com.thevortex.allthetweaks.proxy.MyCons.iconStream(MyCons.java:29) ~[allthetweaks-1.21-2.4.2-_neoforge_1.21.jar%23375!/:_neoforge_1.21] {re:classloading}
	at TRANSFORMER/allthetweaks@2.4.2/com.thevortex.allthetweaks.proxy.MyCons.setWindowIcon(MyCons.java:44) ~[allthetweaks-1.21-2.4.2-_neoforge_1.21.jar%23375!/:_neoforge_1.21] {re:classloading}
	at TRANSFORMER/allthetweaks@2.4.2/com.thevortex.allthetweaks.config.Configuration.onLoad(Configuration.java:141) ~[allthetweaks-1.21-2.4.2-_neoforge_1.21.jar%23375!/:_neoforge_1.21] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%23165!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%23165!/:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:158) ~[loader-4.0.21.jar%23156!/:4.0] {re:mixin}
	at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.config.ModConfig.setConfig(ModConfig.java:69) ~[loader-4.0.21.jar%23156!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.config.ConfigTracker.loadConfig(ConfigTracker.java:197) ~[loader-4.0.21.jar%23156!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.config.ConfigTracker.openConfig(ConfigTracker.java:140) ~[loader-4.0.21.jar%23156!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.config.ConfigTracker.lambda$loadConfigs$2(ConfigTracker.java:124) ~[loader-4.0.21.jar%23156!/:4.0] {}
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:124) ~[loader-4.0.21.jar%23156!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.21/net.neoforged.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:119) ~[loader-4.0.21.jar%23156!/:4.0] {}
	at TRANSFORMER/neoforge@21.0.148/net.neoforged.neoforge.internal.CommonModLoader.lambda$begin$1(CommonModLoader.java:64) ~[neoforge-21.0.148-universal.jar%23366!/:?] {re:classloading}
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
```
Is it possible to fix this error?

**Comment by thevortex** [comment]
full logs please https://mclo.gs
