### ISSUE TITLE
[Bug]: Curios wiped all equipped items from all players

### ISSUE THREAD

**Issue by LordCorellon** [AllTheMods/ATM-10#326]
### Possible Fixes

Yes

### Modpack Version

.38

### What happened?

Play on a dedicated family server, 3 people were playing and the server timed out, attempting to log back in players encountered an "Invalid player data" error.

Stopping and restarting the server allowed for all players to log in, however all equipped curios items disappeared.

Logs only show the following:
<details><summary>Details</summary>
<p>

[23Aug2024 22:30:13.195] [Server thread/ERROR] [net.neoforged.bus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.network.protocol.common.custom.CustomPacketPayload.type()" because the return value of "net.minecraft.network.protocol.common.ClientboundCustomPayloadPacket.payload()" is null
	Index: 0
	Listeners:
		0: net.neoforged.bus.EventListenerFactory$datapackSync/0x00000248e3ebd000@2976f876
		1: dev.technici4n.moderndynamics.attachment.upgrade.AttachmentUpgradesLoader$$Lambda/0x00000248e1f540f8@628700be
		2: net.neoforged.bus.EventListenerFactory$onDpSync/0x00000248e1f58400@735e4fa8
		3: gripe._90.megacells.MEGACells$$Lambda/0x00000248e2b24e48@43f35df2
		4: com.telepathicgrunt.the_bumblezone.neoforge.NeoForgeEventManager$$Lambda/0x00000248e2b9a360@3174fff3
		5: net.p3pp3rf1y.sophisticatedcore.common.CommonEventHandler$$Lambda/0x00000248e2c759e0@63b57adb
		6: net.neoforged.bus.EventListenerFactory$sync/0x00000248e2e28800@225a6933
		7: net.neoforged.bus.EventListenerFactory$onDataSync/0x00000248e314d000@374890fb
		8: net.neoforged.bus.EventListenerFactory$sync/0x00000248e3850400@29637b2c
		9: com.klikli_dev.modonomicon.ModonomiconNeo$$Lambda/0x00000248e3a86f80@4b1ab4d6
		10: net.neoforged.bus.EventListenerFactory$onDataSync/0x00000248e4090400@28c152a7
		11: net.neoforged.bus.EventListenerFactory$sync/0x00000248e4f3cc00@5923a57d
		12: net.neoforged.bus.EventListenerFactory$onDatapackSync/0x00000248e4f3dc00@2a1f29ea
		13: net.neoforged.bus.EventListenerFactory$onDatapackSync/0x00000248e4f4d800@18979d9e
		14: dev.shadowsoffire.placebo.reload.DynamicRegistry$SyncManagement$$Lambda/0x00000248e4f4f6f8@1176e4c2
		15: net.neoforged.bus.EventListenerFactory$onDatapackSyncEvent/0x00000248e500c400@3a61b041
		16: gripe._90.megacells.misc.LavaTransformLogic$$Lambda/0x00000248e5d817d8@66f04428
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.protocol.common.custom.CustomPacketPayload.type()" because the return value of "net.minecraft.network.protocol.common.ClientboundCustomPayloadPacket.payload()" is null
	at TRANSFORMER/neoforge@21.1.23/net.neoforged.neoforge.network.registration.NetworkRegistry.checkPacket(NetworkRegistry.java:436)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:178)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:173)
	at TRANSFORMER/neoforge@21.1.23/net.neoforged.neoforge.network.PacketDistributor.sendToPlayer(PacketDistributor.java:51)
	at TRANSFORMER/kubejs@2101.7.0-build.148/dev.latvian.mods.kubejs.player.KubeJSPlayerEventHandler.lambda$datapackSync$0(KubeJSPlayerEventHandler.java:29)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at TRANSFORMER/kubejs@2101.7.0-build.148/dev.latvian.mods.kubejs.player.KubeJSPlayerEventHandler.datapackSync(KubeJSPlayerEventHandler.java:29)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:205)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:188)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:8)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[23Aug2024 22:30:13.203] [Server thread/ERROR] [net.minecraft.server.network.ServerConfigurationPacketListenerImpl/]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.protocol.common.custom.CustomPacketPayload.type()" because the return value of "net.minecraft.network.protocol.common.ClientboundCustomPayloadPacket.payload()" is null
	at TRANSFORMER/neoforge@21.1.23/net.neoforged.neoforge.network.registration.NetworkRegistry.checkPacket(NetworkRegistry.java:436) ~[neoforge-21.1.23-universal.jar%23344!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:178) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:173) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/neoforge@21.1.23/net.neoforged.neoforge.network.PacketDistributor.sendToPlayer(PacketDistributor.java:51) ~[neoforge-21.1.23-universal.jar%23344!/:?]
	at TRANSFORMER/kubejs@2101.7.0-build.148/dev.latvian.mods.kubejs.player.KubeJSPlayerEventHandler.lambda$datapackSync$0(KubeJSPlayerEventHandler.java:29) ~[kubejs-neoforge-2101.7.0-build.148.jar%23462!/:2101.7.0-build.148]
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at TRANSFORMER/kubejs@2101.7.0-build.148/dev.latvian.mods.kubejs.player.KubeJSPlayerEventHandler.datapackSync(KubeJSPlayerEventHandler.java:29) ~[kubejs-neoforge-2101.7.0-build.148.jar%23462!/:2101.7.0-build.148]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.1.jar%2367!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.1.jar%2367!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:205) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:188) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:8) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23343!/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[23Aug2024 22:30:13.211] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Player lost connection: Invalid player data
[23Aug2024 22:30:13.228] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Player left the game

</p>
</details>

**Comment by alekthefirst** [comment]
Without more information or indications of further issues, i am closing this because of stale issue.
It is probable it was corruption stemming from a different issue entirely, would need the whole log of the session with the initial timeout to verify, and i assume that is no longer available
