### ISSUE TITLE
[Bug]: Server stuck on launch

### ISSUE THREAD

**Issue by Zlababababan** [AllTheMods/ATM-10#607]
### Possible Fixes

Yes

### Modpack Version

0.57

### What happened?

The server never launch and the logs are stuck

[Server thread/ERROR] [minecolonies/]: Failed to parse loot table from ResourceKey[minecraft:loot_table / productivebees:entities/dye_bee]
java.lang.IllegalStateException: Missing element ResourceKey[minecraft:loot_table / productivebees:entities/dye_bee]

It might be an issue with Mine Colonies and Productive Bees
There's this error a ton with different bees

### latest.log

https://gist.github.com/Zlababababan/b4a50b9458bfa6b74d400127a33f9cfa

**Comment by ncottrill** [comment]
Our server is starting and functioning just fine with 10-0.57. The Bumblezone is buggy, however.

**Comment by DerTolleIgel** [comment]
We had the same issue. I tried to upgrade the server and could not start it.
Trying to create completely new server lead to the same result.

**Comment by Zlababababan** [comment]
> Our server is starting and functioning just fine with 10-0.57. The Bumblezone is buggy, however.
> 
> PS. I tested removing the " Additional Lanterns " mod, which is causing conflicts with with the vanilla lantern recipe and now the server will not start. So, if you removed " Additional Lanterns " mods, or disabled it, you must have it enabled and in the pack for the server to start.
> 
> PPS. Any changes to the number of ATM 10 prescribed mods in the server will cause indices to go out of bounds and crash load up.

I also tried to recreate a new server, with a different world, from nothing but I still have the same issue. The server is stuck on start

**Comment by Zlababababan** [comment]
Removing MineColonies "fix" the problem btw

**Comment by ncottrill** [comment]
We have a Linux server running ATM 10 in Pterodactyl containers. We're building Minecolonies actively on our server in ATM 10 while working on the ATM 10 quests. I'm not sure if the environment OS makes a difference, or not. I thought I'd mention this in case it does. 

There are some recipe conflicts that need resolved. Additional Lanterns and Minecolonies disagree on what defines a proper vanilla Minecraft Lantern. So, there's probably some recipe tweaking that needs to be done.

**Comment by Japa2911** [comment]
> We had the same issue. I tried to upgrade the server and could not start it. Trying to create completely new server lead to the same result.

Mesmo problema aqui.. 0.57 e 0.58

**Comment by Caphaldor** [comment]
The Issue persists on 0.60

Debug log:
https://gist.github.com/Caphaldor/fa18b7dacbb061c32cb4ff7d3a7eb045

**Comment by RealMcNugget** [comment]
I'm also having the same issue, happens on all versions between 0.56 and 0.60.

Happens when trying to upgrade my 0.55 server and when starting a fresh one

**Comment by DerTolleIgel** [comment]
> I'm also having the same issue, happens on all versions between 0.56 and 0.60.
> 
> Happens when trying to upgrade my 0.55 server and when starting a fresh one

Interesting, 0.56 works with no issue. Assumption was it had to do with minecolonies and hosting it on Windows. Are you also hosting on Windows?

**Comment by RealMcNugget** [comment]
> > I'm also having the same issue, happens on all versions between 0.56 and 0.60.
> > Happens when trying to upgrade my 0.55 server and when starting a fresh one
> 
> Interesting, 0.56 works with no issue. Assumption was it had to do with minecolonies and hosting it on Windows. Are you also hosting on Windows?

Oh youre right actually - I'm currently running 0.55 and the first upgrade i tried was 0.57. My hosting server is ubuntu 20.04

**Comment by Caphaldor** [comment]
> > I'm also having the same issue, happens on all versions between 0.56 and 0.60.
> > 
> > Happens when trying to upgrade my 0.55 server and when starting a fresh one
> 
> Interesting, 0.56 works with no issue. Assumption was it had to do with minecolonies and hosting it on Windows. Are you also hosting on Windows?

Linux for me too, Ubuntu Docker Container to be precise.

**Comment by Zlababababan** [comment]
After removing Mine Colonies and losing all the blocks in the overworld and putting it back

I still have the errors in the logs of the server but the world is joinable

I'll try to test if I can reproduce the problem again

**Comment by Somicu** [comment]
Any new updates on this?

**Comment by RealMcNugget** [comment]
tried on 0.62 - Same error again:

```
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering Ores 227 166
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering saplings 300
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering plantables 19
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering food 636 717
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering fuel 7000
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering flowers 174
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering items 33472
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering lucky oreBlocks 6
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering recruitment costs
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering diseases
[13:25:57] [Server thread/INFO] [minecolonies/]: Finished discovering compostables 2113
[13:25:57] [Server thread/ERROR] [minecolonies/]: Couldnt analyze animal
java.lang.IllegalArgumentException: Duplicate id value for 17!
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData$Builder.define(SynchedEntityData.java:155) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,re:classloading}
        at TRANSFORMER/ars_elemental@1.21.0-0.7.0.5/alexthw.ars_elemental.common.entity.familiars.FirenandoFamiliar.defineSynchedData(FirenandoFamiliar.java:100) ~[ars_elemental-1.21.0-0.7.0.5.jar%23433!/:1.21.0-0.7.0.5] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.<init>(Entity.java:266) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.LaterLivingEntityMixin from mod the_bumblezone,pl:mixin:APP:enderiobase.mixins.json:LivingEntityMixin from mod enderio_base,pl:mixin:APP:eternal_starlight-common.mixins.json:LivingEntityMixin from mod eternal_starlight,pl:mixin:APP:curios.neoforge.mixins.json:MixinLivingEntity from mod curios,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.LivingEntityAccessor from mod the_bumblezone,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity from mod caelus,pl:mixin:APP:mixins.pneumaticcraft.json:coremods.LivingEntityMixin from mod pneumaticcraft,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor from mod netherportalfix,pl:mixin:APP:ars_nouveau.mixins.json:LivingAccessor from mod ars_nouveau,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity from mod ars_nouveau,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity from mod ars_nouveau,pl:mixin:APP:apothic_attributes.mixins.json:LivingEntityMixin from mod apothic_attributes,pl:mixin:APP:relics.mixins.json:LivingEntityMixin from mod relics,pl:mixin:APP:dummmmmmy-common.mixins.json:LivingEntityMixin from mod dummmmmmy,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity from mod mostructures,pl:mixin:APP:refurbished_furniture.common.mixins.json:LivingEntityMixin from mod refurbished_furniture,pl:mixin:APP:kubejs.mixins.json:LivingEntityMixin from mod kubejs,pl:mixin:APP:mixins.artifacts.common.json:ability.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:ability.hurtsound.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:ability.teleportondeath.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:accessors.LivingEntityAccessor from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:attribute.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:attribute.invincibilityticks.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.neoforge.json:ability.slipresistance.LivingEntityMixin from mod artifacts,pl:mixin:APP:endermanoverhaul.mixins.json:common.LivingEntityMixin from mod endermanoverhaul,pl:mixin:APP:forbidden_arcanus.mixins.json:LivingEntityMixin from mod forbidden_arcanus,pl:mixin:APP:irons_spellbooks.mixins.json:LivingEntityMixin from mod irons_spellbooks,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin from mod expandability,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin from mod expandability,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.LivingEntityMixin from mod the_bumblezone,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.<init>(Mob.java:139) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.MobAccessor from mod the_bumblezone,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.MobAccess from mod pneumaticcraft,pl:mixin:APP:ars_nouveau.mixins.json:MobAccessor from mod ars_nouveau,pl:mixin:APP:ars_nouveau.mixins.json:jar.MobAccessorMixin from mod ars_nouveau,pl:mixin:APP:letmedespawn.mixins.json:MobMixin from mod letmedespawn,pl:mixin:APP:mixins.artifacts.common.json:accessors.MobAccessor from mod artifacts,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin from mod moonlight,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:17) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:computing_frames,re:mixin,re:classloading}
        at TRANSFORMER/ars_nouveau@5.1.0/com.hollingsworth.arsnouveau.common.entity.familiar.FamiliarEntity.<init>(FamiliarEntity.java:65) ~[ars_nouveau-1.21.0-5.1.0-all.jar%23434!/:5.1.0] {re:classloading}
        at TRANSFORMER/ars_elemental@1.21.0-0.7.0.5/alexthw.ars_elemental.common.entity.familiars.FirenandoFamiliar.<init>(FirenandoFamiliar.java:35) ~[ars_elemental-1.21.0-0.7.0.5.jar%23433!/:1.21.0-0.7.0.5] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType.create(EntityType.java:1097) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,xf:fml:default,re:classloading,xf:fml:default,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.EntityTypeMixin from mod the_bumblezone,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType from mod architectury,pl:mixin:APP:kubejs.mixins.json:EntityTypeMixin from mod kubejs,pl:mixin:A}
        at TRANSFORMER/minecolonies@1.1.721-1.21.1-snapshot/com.minecolonies.core.colony.crafting.RecipeAnalyzer.createAnimals(RecipeAnalyzer.java:120) ~[minecolonies-1.1.721-1.21.1-snapshot.jar%23576!/:1.1.721-1.21.1-snapshot] {re:classloading}
        at TRANSFORMER/minecolonies@1.1.721-1.21.1-snapshot/com.minecolonies.core.colony.crafting.CustomRecipeManager.buildLootData(CustomRecipeManager.java:307) ~[minecolonies-1.1.721-1.21.1-snapshot.jar%23576!/:1.1.721-1.21.1-snapshot] {re:classloading}
        at TRANSFORMER/minecolonies@1.1.721-1.21.1-snapshot/com.minecolonies.core.event.DataPackSyncEventHandler$ServerEvents.discoverCompatLists(DataPackSyncEventHandler.java:62) ~[minecolonies-1.1.721-1.21.1-snapshot.jar%23576!/:1.1.721-1.21.1-snapshot] {re:classloading}
        at TRANSFORMER/minecolonies@1.1.721-1.21.1-snapshot/com.minecolonies.core.event.DataPackSyncEventHandler$ServerEvents.load(DataPackSyncEventHandler.java:133) ~[minecolonies-1.1.721-1.21.1-snapshot.jar%23576!/:1.1.721-1.21.1-snapshot] {re:classloading}
        at TRANSFORMER/minecolonies@1.1.721-1.21.1-snapshot/com.minecolonies.core.event.FMLEventHandler.onServerTick(FMLEventHandler.java:28) ~[minecolonies-1.1.721-1.21.1-snapshot.jar%23576!/:1.1.721-1.21.1-snapshot] {re:classloading}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2367!/:?] {}
        at TRANSFORMER/neoforge@21.1.65/net.neoforged.neoforge.event.EventHooks.fireServerTickPre(EventHooks.java:992) ~[neoforge-21.1.65-universal.jar%23402!/:?] {re:mixin,re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:915) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23401!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}

```

**Comment by DerTolleIgel** [comment]
Hi,
as said before, I have the same. However, I was told, that it actually starts, also it does not say, that the server start was done successfully. Just leave it like this and try to join the server..

**Comment by alekthefirst** [comment]
These servers seem to be starting just fine, `Finished discovering compostables 2113` is usually the last line of a successful startup, and then the duplicate ID values and a ton of other errors pop up associated with world generation
