### ISSUE TITLE
[Crash for potion brewer industrial foregoing

### ISSUE THREAD

**Issue by ANDREWK-12** [AllTheMods/ATM-10#681]
### Possible Fixes

Yes

### Modpack Version

.61

### What happened?

My game closed after I put the industrial foregoing machine to work and now I can't enter the world anymore

### Crash Log

<script src="https://gist.github.com/ANDREWK-12/0b84853631be5c818cc0dcb96e81529e.js"></script>

### Latest.Log

<script src="https://gist.github.com/ANDREWK-12/54d90d087a9ebb5c813d1cbccd6abe5e.js"></script>

**Comment by Lupedosa** [comment]
I have the exact same issue

**Comment by ncottrill** [comment]
Same problem. The Potion Brewer is an issue:

Time: 2024-10-12 16:48:00
Description: Ticking block entity

java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?] {}
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?] {}
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?] {}
	at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?] {re:mixin}
	at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.NonNullList.get(NonNullList.java:66) ~[server-1.21.1-20240808.144430-srg.jar%23413!/:?] {re:mixin,re:computing_frames,re:classloading}
	at TRANSFORMER/industrialforegoing@1.21-3.6.13/com.buuz135.industrial.block.resourceproduction.tile.PotionBrewerTile.brewPotions(PotionBrewerTile.java:232) ~[industrialforegoing-1.21-3.6.13.jar%23550!/:?] {re:classloading}
	at TRANSFORMER/industrialforegoing@1.21-3.6.13/com.buuz135.industrial.block.resourceproduction.tile.PotionBrewerTile.lambda$onFinish$11(PotionBrewerTile.java:178) ~[industrialforegoing-1.21-3.6.13.jar%23550!/:?] {re:classloading}
	at TRANSFORMER/industrialforegoing@1.21-3.6.13/com.buuz135.industrial.block.tile.IndustrialProcessingTile.lambda$new$4(IndustrialProcessingTile.java:92) ~[industrialforegoing-1.21-3.6.13.jar%23550!/:?] {re:classloading}
	at TRANSFORMER/titanium@4.0.21/com.hrznstudio.titanium.component.progress.ProgressBarComponent.tickBar(ProgressBarComponent.java:187) ~[titanium-1.21-4.0.21.jar%23686!/:4.0.21] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/titanium@4.0.21/com.hrznstudio.titanium.component.progress.MultiProgressBarHandler.update(MultiProgressBarHandler.java:43) ~[titanium-1.21-4.0.21.jar%23686!/:4.0.21] {re:classloading}
	at TRANSFORMER/titanium@4.0.21/com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:224) ~[titanium-1.21-4.0.21.jar%23686!/:4.0.21] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/titanium@4.0.21/com.hrznstudio.titanium.block.tile.ActiveTile.serverTick(ActiveTile.java:73) ~[titanium-1.21-4.0.21.jar%23686!/:4.0.21] {re:classloading,pl:runtimedistcleaner:A}
	at TRANSFORMER/titanium@4.0.21/com.hrznstudio.titanium.block.BasicTileBlock.lambda$getTicker$5(BasicTileBlock.java:83) ~[titanium-1.21-4.0.21.jar%23686!/:4.0.21] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:706) ~[server-1.21.1-20240808.144430-srg.jar%23413!/:?] {re:mixin,re:classloading,pl:mixin:APP:polymorph.mixins.json:MixinLevelChunk from mod polymorph,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:783) ~[server-1.21.1-20240808.144430-srg.jar%23413!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.redirect$bim000$observable$redirectTick(Level.java:2318) ~[server-1.21.1-20240808.144430-srg.jar%23413!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:LevelMixin from mod mffs,pl:mixin:APP:refurbished_furniture.common.mixins.json:LevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:LevelMixin from mod observable,pl:mixin:APP:kubejs.mixins.json:LevelMixin from mod kubejs,pl:mixin:APP:xycraft_core.mixins.json:LevelRainShieldMixin from mod xycraft_core,pl:mixin:APP:the_bumblezone-common.mixins.json:world.LevelMixin from mod the_bumblezone,pl:mixin:A}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.tickBlockEntities(Level.java:559) ~[server-1.21.1-20240808.144430-srg.jar%23413!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:LevelMixin from mod mffs,pl:mixin:APP:refurbished_furniture.common.mixins.json:LevelMixin from mod refurbished_furniture,pl:mixin:APP:observable.common.json:LevelMixin from mod observable,pl:mixin:APP:kubejs.mixins.json:LevelMixin from mod kubejs,pl:mixin:APP:xycraft_core.mixins.json:LevelRainShieldMixin from mod xycraft_core,pl:mixin:APP:the_bumblezone-common.mixins.json:world.LevelMixin from mod the_bumblezone,pl:mixin:A}
