### ISSUE TITLE
[Bug]: Silent Gear Tools + FTB Ultimine Causing Block Drop Failure

### ISSUE THREAD

**Issue by TheJadedWriter** [AllTheMods/ATM-10#707]
### Possible Fixes

Yes

### Modpack Version

0.64

### What happened?

After initiating a block-breaking event with FTB Ultimine and Silent Gear tools, the mined blocks do not drop any items. This happens consistently across different blocks and dimensions.

If I close the server and client then relaunch both it is fixed. just closing the client and then restarting the client and rejoining the server does not work.

### latest.log

https://gist.github.com/TheJadedWriter/c71737473f056a43756861992f45a27f

**Comment by Caphaldor** [comment]
Can confirm this. Only server restart needed for me to fix.

**Comment by PoppyHandsley** [comment]
This also happened for me, further to that it also impacted loot being dropped etc until the server was restarted

**Comment by Redeye123** [comment]
Can confirm one player started mining with silentgear pickaxe with ultimine and everyone online noticed blocks not dropping

**Comment by DropDeadCriminal** [comment]
Seeing this as well. Server restart resolves.

**Comment by jacksondarman** [comment]
Can confirm this as well. Server restart does fix it but I'd like to know if a more permanent solution can be used (besides not using FTB Ultimine on Silent Gear tools ;) )

**Comment by jinkhya** [comment]
Hello, 
Some players on my server also had this issue so I went through the server logs when it started happening and here's what I found : 
```
[08Oct2024 03:25:50.907] [Server thread/ERROR] [net.minecraft.network.protocol.game.ServerPacketListener/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundPlayerActionPacket@73e4d319, suppressing error
java.lang.IllegalStateException: Cannot get config value before config is loaded.
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[guava-32.1.2-jre.jar%2383!/:?]
	at TRANSFORMER/neoforge@21.1.65/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.getRaw(ModConfigSpec.java:1234) ~[neoforge-21.1.65-universal.jar%23413!/:?]
	at TRANSFORMER/neoforge@21.1.65/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.get(ModConfigSpec.java:1221) ~[neoforge-21.1.65-universal.jar%23413!/:?]
	at TRANSFORMER/silentgear@4.0.2/net.silentchaos512.gear.util.GearHelper.onDamageFactorChange(GearHelper.java:293) ~[silent-gear-1.21.1-neoforge-4.0.2.jar%23658!/:?]
	at TRANSFORMER/silentgear@4.0.2/net.silentchaos512.gear.util.GearHelper.attemptDamage(GearHelper.java:247) ~[silent-gear-1.21.1-neoforge-4.0.2.jar%23658!/:?]
	at TRANSFORMER/silentgear@4.0.2/net.silentchaos512.gear.util.GearHelper.onBlockDestroyed(GearHelper.java:456) ~[silent-gear-1.21.1-neoforge-4.0.2.jar%23658!/:?]
	at TRANSFORMER/silentgear@4.0.2/net.silentchaos512.gear.item.gear.GearPickaxeItem.mineBlock(GearPickaxeItem.java:113) ~[silent-gear-1.21.1-neoforge-4.0.2.jar%23658!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.mineBlock(ItemStack.java:539) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:270) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/ftbultimine@2101.1.1/dev.ftb.mods.ftbultimine.FTBUltimine.blockBroken(FTBUltimine.java:239) ~[ftb-ultimine-neoforge-2101.1.1.jar%23528!/:?]
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source) ~[?:?]
	at TRANSFORMER/architectury@13.0.6/dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53) ~[architectury-13.0.6-neoforge.jar%23443!/:?]
	at TRANSFORMER/architectury@13.0.6/dev.architectury.event.EventFactory$2.handleInvocation(EventFactory.java:81) ~[architectury-13.0.6-neoforge.jar%23443!/:?]
	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87) ~[guava-32.1.2-jre.jar%2383!/:?]
	at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy157.breakBlock(Unknown Source) ~[?:?]
	at TRANSFORMER/architectury@13.0.6/dev.architectury.event.forge.EventHandlerImplCommon.event(EventHandlerImplCommon.java:356) ~[architectury-13.0.6-neoforge.jar%23443!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.SubscribeEventListener.invoke(SubscribeEventListener.java:49) ~[bus-8.0.2.jar%2367!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2367!/:?]
	at TRANSFORMER/neoforge@21.1.65/net.neoforged.neoforge.common.CommonHooks.fireBlockBreak(CommonHooks.java:583) ~[neoforge-21.1.65-universal.jar%23413!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:249) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:239) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:210) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1081) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:50) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:10) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:872) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:170) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:855) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:849) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:821) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:826) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:712) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23412!/:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```
I hope that helps.
Best regards,
Jin

**Comment by Caphaldor** [comment]
Tested with Silent Gear 4.0.3. Works fine now, the modpack needs the update now.

**Comment by TheBedrockMaster** [comment]
Can someone else test this?
