### ISSUE TITLE
[Bug]: Server Version 1.0 Crashes On Start

### ISSUE THREAD

**Issue by BrotalityG** [AllTheMods/ATM-10#777]
### Possible Fixes

Yes

### Modpack Version

1.0

### What happened?

Fresh install on a brand new server; on launch gives this error:

```
[00:16:59] [Server thread/ERROR] [minecolonies/]: Couldnt analyze animal
java.lang.IllegalArgumentException: Duplicate id value for 17!
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData$Builder.define(SynchedEntityData.java:155) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:mixin,re:classloading}
        at TRANSFORMER/ars_elemental@1.21.0-0.7.0.5/alexthw.ars_elemental.common.entity.familiars.FirenandoFamiliar.defineSynchedData(FirenandoFamiliar.java:100) ~[ars_elemental-1.21.0-0.7.0.5.jar%23453!/:1.21.0-0.7.0.5] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.<init>(Entity.java:266) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.LaterLivingEntityMixin from mod the_bumblezone,pl:mixin:APP:enderiobase.mixins.json:LivingEntityMixin from mod enderio_base,pl:mixin:APP:eternal_starlight-common.mixins.json:LivingEntityMixin from mod eternal_starlight,pl:mixin:APP:curios.neoforge.mixins.json:MixinLivingEntity from mod curios,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin from mod tombstone,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.LivingEntityAccessor from mod the_bumblezone,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity from mod caelus,pl:mixin:APP:mixins.pneumaticcraft.json:coremods.LivingEntityMixin from mod pneumaticcraft,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor from mod netherportalfix,pl:mixin:APP:ars_nouveau.mixins.json:LivingAccessor from mod ars_nouveau,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity from mod ars_nouveau,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity from mod ars_nouveau,pl:mixin:APP:apothic_attributes.mixins.json:LivingEntityMixin from mod apothic_attributes,pl:mixin:APP:relics.mixins.json:LivingEntityMixin from mod relics,pl:mixin:APP:dummmmmmy-common.mixins.json:LivingEntityMixin from mod dummmmmmy,pl:mixin:APP:mostructures.mixins.json:MixinLivingEntity from mod mostructures,pl:mixin:APP:refurbished_furniture.common.mixins.json:LivingEntityMixin from mod refurbished_furniture,pl:mixin:APP:kubejs.mixins.json:LivingEntityMixin from mod kubejs,pl:mixin:APP:mixins.artifacts.common.json:ability.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:ability.hurtsound.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:ability.teleportondeath.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:accessors.LivingEntityAccessor from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:attribute.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.common.json:attribute.invincibilityticks.LivingEntityMixin from mod artifacts,pl:mixin:APP:mixins.artifacts.neoforge.json:ability.slipresistance.LivingEntityMixin from mod artifacts,pl:mixin:APP:betterdeserttemples.mixins.json:pharaoh.LivingEntityMixin from mod betterdeserttemples,pl:mixin:APP:endermanoverhaul.mixins.json:common.LivingEntityMixin from mod endermanoverhaul,pl:mixin:APP:forbidden_arcanus.mixins.json:LivingEntityMixin from mod forbidden_arcanus,pl:mixin:APP:irons_spellbooks.mixins.json:LivingEntityMixin from mod irons_spellbooks,pl:mixin:APP:expandability-common.mixins.json:swimming.LivingEntityMixin from mod expandability,pl:mixin:APP:expandability.mixins.json:swimming.LivingEntityMixin from mod expandability,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.LivingEntityMixin from mod the_bumblezone,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.<init>(Mob.java:139) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:MobMixin from mod tombstone,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.MobAccessor from mod the_bumblezone,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.MobAccess from mod pneumaticcraft,pl:mixin:APP:livingthings.mixins.json:entity.MobAccessor from mod livingthings,pl:mixin:APP:ars_nouveau.mixins.json:MobAccessor from mod ars_nouveau,pl:mixin:APP:ars_nouveau.mixins.json:jar.MobAccessorMixin from mod ars_nouveau,pl:mixin:APP:letmedespawn.mixins.json:MobMixin from mod letmedespawn,pl:mixin:APP:mixins.artifacts.common.json:accessors.MobAccessor from mod artifacts,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin from mod moonlight,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:17) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:computing_frames,re:mixin,re:classloading}
        at TRANSFORMER/ars_nouveau@5.1.0/com.hollingsworth.arsnouveau.common.entity.familiar.FamiliarEntity.<init>(FamiliarEntity.java:65) ~[ars_nouveau-1.21.0-5.1.0-all.jar%23454!/:5.1.0] {re:classloading}
        at TRANSFORMER/ars_elemental@1.21.0-0.7.0.5/alexthw.ars_elemental.common.entity.familiars.FirenandoFamiliar.<init>(FirenandoFamiliar.java:35) ~[ars_elemental-1.21.0-0.7.0.5.jar%23453!/:1.21.0-0.7.0.5] {re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.EntityType.create(EntityType.java:1097) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:mixin,xf:fml:default,re:classloading,xf:fml:default,pl:mixin:APP:the_bumblezone-common.mixins.json:entities.EntityTypeMixin from mod the_bumblezone,pl:mixin:APP:architectury-common.mixins.json:inject.MixinEntityType from mod architectury,pl:mixin:APP:kubejs.mixins.json:EntityTypeMixin from mod kubejs,pl:mixin:A}
        at TRANSFORMER/minecolonies@1.1.724-1.21.1-snapshot/com.minecolonies.core.colony.crafting.RecipeAnalyzer.createAnimals(RecipeAnalyzer.java:120) ~[minecolonies-1.1.724-1.21.1-snapshot.jar%23597!/:1.1.724-1.21.1-snapshot] {re:classloading}
        at TRANSFORMER/minecolonies@1.1.724-1.21.1-snapshot/com.minecolonies.core.colony.crafting.CustomRecipeManager.buildLootData(CustomRecipeManager.java:307) ~[minecolonies-1.1.724-1.21.1-snapshot.jar%23597!/:1.1.724-1.21.1-snapshot] {re:classloading}
        at TRANSFORMER/minecolonies@1.1.724-1.21.1-snapshot/com.minecolonies.core.event.DataPackSyncEventHandler$ServerEvents.discoverCompatLists(DataPackSyncEventHandler.java:62) ~[minecolonies-1.1.724-1.21.1-snapshot.jar%23597!/:1.1.724-1.21.1-snapshot] {re:classloading}
        at TRANSFORMER/minecolonies@1.1.724-1.21.1-snapshot/com.minecolonies.core.event.DataPackSyncEventHandler$ServerEvents.load(DataPackSyncEventHandler.java:133) ~[minecolonies-1.1.724-1.21.1-snapshot.jar%23597!/:1.1.724-1.21.1-snapshot] {re:classloading}
        at TRANSFORMER/minecolonies@1.1.724-1.21.1-snapshot/com.minecolonies.core.event.FMLEventHandler.onServerTick(FMLEventHandler.java:28) ~[minecolonies-1.1.724-1.21.1-snapshot.jar%23597!/:1.1.724-1.21.1-snapshot] {re:classloading}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?] {}
        at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2367!/:?] {}
        at TRANSFORMER/neoforge@21.1.68/net.neoforged.neoforge.event.EventHooks.fireServerTickPre(EventHooks.java:992) ~[neoforge-21.1.68-universal.jar%23420!/:?] {re:mixin,re:classloading}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:915) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23419!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] {re:mixin}
```

I do not know what is causing it, however it takes a solid minute or two of launching to actually get to this point.

### latest.log

https://gist.github.com/BrotalityG/7c53633e8fa5328726f7eb32f54ee0a0

**Comment by BrotalityG** [comment]
Resolved; Was not crashing rather had networking issues.

**Comment by Clubprisme** [comment]
Hello I have the same issue
How do fixe this please ?

**Comment by Walshie1980** [comment]
Same, having same issue.

**Comment by BrotalityG** [comment]
Replying only to mark solution for those still struggling: The issue is not that your server is not launching, if you see this error, it has successfully launched, the problem is that your network configuration is not posting the server. If you are hosting locally, ensure you have port forwarded correctly. If you are hosting on a website, try direct connecting to the IP. It should load fine. If it doesn't, make sure your modpack version you're joining with matches the one on the server (i.e. 1.1 will have issues joining a 1.0 server, and will give similar issues).

The server itself is not crashing. It is a configuration error on your end.
