### ISSUE TITLE
[Crash]: Creative Mode Search crashes when typing

### ISSUE THREAD

**Issue by embermctillhawk** [AllTheMods/ATM-10#821]
### Possible Fixes

Yes

### Modpack Version

1.2

### What happened?

Step 1: install the pack when trying to investigate a bug report
Step 2: run the pack
Step 3: make a new world
Step 4: use creative mode
Step 5: open inventory
Step 6: switch to search tab
Step 7: attempt to type
Step 8: stare blankly at your desktop after the game closes

Edit: Step 9: try it two more times and get the same result

### Crash Log

https://gist.github.com/embermctillhawk/2bf0ba5fb3d71ee6bd02b99ba65c3453#file-crash-2024-10-18_21-26-50-client-txt

### Latest.Log

https://gist.github.com/embermctillhawk/5daa80ed094b6fb5b8a60b5f9768b3d5#file-latest-log

**Comment by ReeViiS69** [comment]
deleting profile and backups in curseforge launcher(BACKUP UR WORLDS ETC. MANUALY before deleting!)
Download desired Version, we tried with 1.9 and 1.11.
Enjoy

**Comment by embermctillhawk** [comment]
Updated to 1.11, same crash.
Checked the crash log more closely. It looks like Super Factory Manager is calling GLFW in the wrong thread.

`...
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar%23101!/:build 5] {}
	at MC-BOOTSTRAP/org.lwjgl@3.3.3+5/org.lwjgl.system.JNI.invokePI(Native Method) ~[lwjgl-3.3.3.jar%23113!/:build 5] {}
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3746) ~[lwjgl-glfw-3.3.3.jar%23101!/:build 5] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.InputConstants.isKeyDown(InputConstants.java:473) ~[client-1.21.1-20240808.144430-srg.jar%23517!/:?] {re:classloading}
	at TRANSFORMER/sfm@4.19.0/ca.teamdman.sfm.client.ClientStuff.isMoreInfoKeyDown(ClientStuff.java:115) ~[Super%20Factory%20Manager-1.21.1-4.19.0.jar%23808!/:?] {re:classloading}
	at TRANSFORMER/sfm@4.19.0/ca.teamdman.sfm.common.item.DiskItem.appendHoverText(DiskItem.java:177) ~[Super%20Factory%20Manager-1.21.1-4.19.0.jar%23808!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.getTooltipLines(ItemStack.java:770) ~[client-1.21.1-20240808.144430-srg.jar%23517!/:?] { ###removed for brevity### }
...`

Tried removing SFM. Almost an identical crash occurs, this time from Modular Routers.

`...
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar%23101!/:build 5] {}
	at MC-BOOTSTRAP/org.lwjgl@3.3.3+5/org.lwjgl.system.JNI.invokePI(Native Method) ~[lwjgl-3.3.3.jar%23113!/:build 5] {}
	at MC-BOOTSTRAP/org.lwjgl.glfw@3.3.3+5/org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3746) ~[lwjgl-glfw-3.3.3.jar%23101!/:build 5] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/com.mojang.blaze3d.platform.InputConstants.isKeyDown(InputConstants.java:473) ~[client-1.21.1-20240808.144430-srg.jar%23546!/:?] {re:classloading}
	at TRANSFORMER/modularrouters@13.0.3/me.desht.modularrouters.client.util.ClientUtil.isKeyDown(ClientUtil.java:72) ~[modular-routers-13.0.3+mc1.21.jar%23772!/:?] {re:classloading}
	at TRANSFORMER/modularrouters@13.0.3/me.desht.modularrouters.item.MRBaseItem.appendHoverText(MRBaseItem.java:30) ~[modular-routers-13.0.3+mc1.21.jar%23772!/:?] {re:classloading}
	at TRANSFORMER/modularrouters@13.0.3/me.desht.modularrouters.item.module.ModuleItem.appendHoverText(ModuleItem.java:138) ~[modular-routers-13.0.3+mc1.21.jar%23772!/:?] {re:classloading}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.getTooltipLines(ItemStack.java:770) ~[client-1.21.1-20240808.144430-srg.jar%23546!/:?] { ###removed for brevity### }
...`

Both of them look like they're calling `com.mojang.blaze3d.platform.InputConstants.isKeyDown(InputConstants.java:473)` from `net.minecraft.world.item.ItemStack.getTooltipLines(ItemStack.java:770)`. Not sure if another mod is throwing something off so this doesn't happen in isolation, will do further testing.

Also tried re-adding SFM, same crash. So it happens with either SFM or MR independently, give or take some possible third mod's interference.
