### ISSUE TITLE
[Bug]: Integrated Dynamics 

### ISSUE THREAD

**Issue by desure85nt** [AllTheMods/ATM-10#975]
### Possible Fixes

Yes

### Modpack Version

1.11, 1.12
### What happened?

After open Integrated Dynamics game  exit in choose server menu

### latest.log

https://gist.github.com/desure85nt/217f8aee451f651fdfd4d352d0eb2d91

**Comment by desure85nt** [comment]
[29Oct2024 20:32:48.565] [Render thread/INFO] [net.minecraft.advancements.AdvancementTree/]: Loaded 463 advancements
[29Oct2024 20:32:59.287] [Netty Local Client IO #0/ERROR] [net.minecraft.network.Connection/]: Exception caught in connection
io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:custom_payload'
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:38) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:14) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:31) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[netty-codec-4.1.97.Final.jar%23134!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[netty-codec-4.1.97.Final.jar%23134!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.codec@4.1.97.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.97.Final.jar%23134!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar%23136!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.handler@4.1.97.Final/io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar%23136!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23135!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23135!/:4.1.97.Final]
	at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23135!/:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.RuntimeException: Failed decoding custom payload integratedterminals:terminal_storage_ingredient_change_event: org.cyclops.cyclopscore.network.PacketCodecException: An exception occurred during decoding of packet org.cyclops.integratedterminals.network.packet.TerminalStorageIngredientChangeEventPacket@6974ce1b
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:55) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	... 26 more
Caused by: org.cyclops.cyclopscore.network.PacketCodecException: An exception occurred during decoding of packet org.cyclops.integratedterminals.network.packet.TerminalStorageIngredientChangeEventPacket@6974ce1b
	at TRANSFORMER/cyclopscore@1.25.2/org.cyclops.cyclopscore.network.PacketBase.lambda$getCodec$0(PacketBase.java:79) ~[cyclopscore-1.21.1-neoforge-1.25.2.jar%23616!/:1.25.2]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$2.decode(StreamCodec.java:37) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	... 26 more
Caused by: net.minecraft.nbt.NbtAccounterException: Tried to read NBT tag that was too big; tried to allocate: 2097122 + 36 bytes where max allowed: 2097152
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.NbtAccounter.accountBytes(NbtAccounter.java:31) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.CompoundTag$1.loadCompound(CompoundTag.java:64) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:41) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:35) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.ListTag$1.loadList(ListTag.java:48) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.ListTag$1.load(ListTag.java:31) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.ListTag$1.load(ListTag.java:26) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.CompoundTag.readNamedTagData(CompoundTag.java:513) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.CompoundTag$1.loadCompound(CompoundTag.java:62) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:41) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.CompoundTag$1.load(CompoundTag.java:35) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.NbtIo.readTagSafe(NbtIo.java:193) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.nbt.NbtIo.readAnyTag(NbtIo.java:157) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:537) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:526) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.FriendlyByteBuf.readNbt(FriendlyByteBuf.java:521) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/cyclopscore@1.25.2/org.cyclops.cyclopscore.network.PacketCodecs$12.decode(PacketCodecs.java:310) ~[cyclopscore-1.21.1-neoforge-1.25.2.jar%23616!/:1.25.2]
	at TRANSFORMER/cyclopscore@1.25.2/org.cyclops.cyclopscore.network.PacketCodec.lambda$decode$1(PacketCodec.java:118) ~[cyclopscore-1.21.1-neoforge-1.25.2.jar%23616!/:1.25.2]
	at TRANSFORMER/cyclopscore@1.25.2/org.cyclops.cyclopscore.network.PacketCodec.loopCodecFields(PacketCodec.java:98) ~[cyclopscore-1.21.1-neoforge-1.25.2.jar%23616!/:1.25.2]
	at TRANSFORMER/cyclopscore@1.25.2/org.cyclops.cyclopscore.network.PacketCodec.decode(PacketCodec.java:117) ~[cyclopscore-1.21.1-neoforge-1.25.2.jar%23616!/:1.25.2]
	at TRANSFORMER/cyclopscore@1.25.2/org.cyclops.cyclopscore.network.PacketBase.lambda$getCodec$0(PacketBase.java:77) ~[cyclopscore-1.21.1-neoforge-1.25.2.jar%23616!/:1.25.2]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$2.decode(StreamCodec.java:37) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:53) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.decode(CustomPacketPayload.java:29) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$4.decode(StreamCodec.java:76) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:91) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.StreamCodec$5.decode(StreamCodec.java:87) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.codec.IdDispatchCodec.decode(IdDispatchCodec.java:36) ~[client-1.21.1-20240808.144430-srg.jar%23535!/:?]
	... 26 more
[29Oct2024 20:32:59.334] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: desure85 has made the advancement [GUI Simulator 9000]
[29Oct2024 20:32:59.657] [Netty Local Client IO #0/ERROR] [net.minecraft.CrashReport/]: Negative index in crash report handler (27/31)
[29Oct2024 20:32:59.688] [Netty Local Client IO #0/FATAL] [net.neoforged.neoforge.common.NeoForgeMod/]: Preparing crash report with UUID 47271180-636d-443a-ac86-a879760cfdf6
[29Oct2024 20:32:59.704] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: desure85 lost connection: Disconnected
[29Oct2024 20:32:59.704] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: desure85 left the game
[29Oct2024 20:32:59.712] [Render thread/INFO] [mezz.jei.neoforge.startup.StartEventObserver/]: JEI StartEventObserver received class net.neoforged.neoforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[29Oct2024 20:32:59.712] [Render thread/INFO] [mezz.jei.neoforge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to LISTENING
[29Oct2024 20:32:59.712] [Render thread/INFO] [mezz.jei.library.startup.JeiStarter/]: Stopping JEI
[29Oct2024 20:32:59.712] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable...
[29Oct2024 20:32:59.715] [Render thread/INFO] [mezz.jei.neoforge.plugins.neoforge.NeoForgeGuiPlugin/]: Stopping JEI GUI
[29Oct2024 20:32:59.726] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable took 13.70 ms
[29Oct2024 20:32:59.734] [Render thread/INFO] [minecolonies/]: Removed all colony views
[29Oct2024 20:32:59.788] [Server thread/INFO] [net.minecraft.server.network.ServerCommonPacketListenerImpl/]: Stopping singleplayer server as player logged out
[29Oct2024 20:32:59.936] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[29Oct2024 20:32:59.937] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[29Oct2024 20:32:59.937] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[29Oct2024 20:33:00.310] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[29Oct2024 20:33:00.344] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[29Oct2024 20:33:00.345] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/hyperbox:ea1a5356-c331-435d-a2c8-a35d5b18dc73/mobile_base
[29Oct2024 20:33:00.364] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/hyperbox:ea1a5356-c331-435d-a2c8-a35d5b18dc73/storage
[29Oct2024 20:33:00.377] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/mahoutsukai:reality_marble
[29Oct2024 20:33:00.378] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/deeperdarker:otherside
[29Oct2024 20:33:00.379] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/allthemodium:mining
[29Oct2024 20:33:00.381] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/hyperbox:ea1a5356-c331-435d-a2c8-a35d5b18dc73/storage3
[29Oct2024 20:33:00.393] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/the_bumblezone:the_bumblezone
[29Oct2024 20:33:00.394] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/allthemodium:the_other
[29Oct2024 20:33:00.395] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/undergarden:undergarden
[29Oct2024 20:33:00.396] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/allthemodium:the_beyond
[29Oct2024 20:33:00.397] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[29Oct2024 20:33:00.398] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/eternal_starlight:starlight
[29Oct2024 20:33:00.400] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/hyperbox:ea1a5356-c331-435d-a2c8-a35d5b18dc73/storage2
[29Oct2024 20:33:00.411] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[New World]'/ae2:spatial_storage
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mobile_base): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (storage): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (reality_marble): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (otherside): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (mining): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (storage3): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (the_bumblezone): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (the_other): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (undergarden): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (the_beyond): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (starlight): All chunks are saved
[29Oct2024 20:33:00.444] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (storage2): All chunks are saved
[29Oct2024 20:33:00.445] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[29Oct2024 20:33:00.445] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[29Oct2024 20:33:00.892] [Server thread/INFO] [Framework/]: Unloading server configs...
[29Oct2024 20:33:00.893] [Server thread/INFO] [Framework/]: Sending config unload event for refurbished_furniture.server.toml
[29Oct2024 20:33:00.926] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads

**Comment by desure85nt** [comment]
https://www.curseforge.com/minecraft/mc-mods/packet-fixer fix it
